
export const countries = [
  { value: 'afghanistan', label: 'Afghanistan', phone: '93', code: 'AF', emoji: '🇦🇫' },
  { value: 'albania', label: 'Albania', phone: '355', code: 'AL', emoji: '🇦🇱' },
  { value: 'algeria', label: 'Algeria', phone: '213', code: 'DZ', emoji: '🇩🇿' },
  { value: 'american-samoa', label: 'American Samoa', phone: '1-684', code: 'AS', emoji: '🇦🇸' },
  { value: 'andorra', label: 'Andorra', phone: '376', code: 'AD', emoji: '🇦🇩' },
  { value: 'angola', label: 'Angola', phone: '244', code: 'AO', emoji: '🇦🇴' },
  { value: 'anguilla', label: 'Anguilla', phone: '1-264', code: 'AI', emoji: '🇦🇮' },
  { value: 'antarctica', label: 'Antarctica', phone: '672', code: 'AQ', emoji: '🇦🇶' },
  { value: 'antigua-and-barbuda', label: 'Antigua and Barbuda', phone: '1-268', code: 'AG', emoji: '🇦🇬' },
  { value: 'argentina', label: 'Argentina', phone: '54', code: 'AR', emoji: '🇦🇷' },
  { value: 'armenia', label: 'Armenia', phone: '374', code: 'AM', emoji: '🇦🇲' },
  { value: 'aruba', label: 'Aruba', phone: '297', code: 'AW', emoji: '🇦🇼' },
  { value: 'australia', label: 'Australia', phone: '61', code: 'AU', emoji: '🇦🇺' },
  { value: 'austria', label: 'Austria', phone: '43', code: 'AT', emoji: '🇦🇹' },
  { value: 'azerbaijan', label: 'Azerbaijan', phone: '994', code: 'AZ', emoji: '🇦🇿' },
  { value: 'bahamas', label: 'Bahamas', phone: '1-242', code: 'BS', emoji: '🇧🇸' },
  { value: 'bahrain', label: 'Bahrain', phone: '973', code: 'BH', emoji: '🇧🇭' },
  { value: 'bangladesh', label: 'Bangladesh', phone: '880', code: 'BD', emoji: '🇧🇩' },
  { value: 'barbados', label: 'Barbados', phone: '1-246', code: 'BB', emoji: '🇧🇧' },
  { value: 'belarus', label: 'Belarus', phone: '375', code: 'BY', emoji: '🇧🇾' },
  { value: 'belgium', label: 'Belgium', phone: '32', code: 'BE', emoji: '🇧🇪' },
  { value: 'belize', label: 'Belize', phone: '501', code: 'BZ', emoji: '🇧🇿' },
  { value: 'benin', label: 'Benin', phone: '229', code: 'BJ', emoji: '🇧🇯' },
  { value: 'bermuda', label: 'Bermuda', phone: '1-441', code: 'BM', emoji: '🇧🇲' },
  { value: 'bhutan', label: 'Bhutan', phone: '975', code: 'BT', emoji: '🇧🇹' },
  { value: 'bolivia', label: 'Bolivia', phone: '591', code: 'BO', emoji: '🇧🇴' },
  { value: 'bosnia-and-herzegovina', label: 'Bosnia and Herzegovina', phone: '387', code: 'BA', emoji: '🇧🇦' },
  { value: 'botswana', label: 'Botswana', phone: '267', code: 'BW', emoji: '🇧🇼' },
  { value: 'brazil', label: 'Brazil', phone: '55', code: 'BR', emoji: '🇧🇷' },
  { value: 'british-indian-ocean-territory', label: 'British Indian Ocean Territory', phone: '246', code: 'IO', emoji: '🇮🇴' },
  { value: 'british-virgin-islands', label: 'British Virgin Islands', phone: '1-284', code: 'VG', emoji: '🇻🇬' },
  { value: 'brunei', label: 'Brunei', phone: '673', code: 'BN', emoji: '🇧🇳' },
  { value: 'bulgaria', label: 'Bulgaria', phone: '359', code: 'BG', emoji: '🇧🇬' },
  { value: 'burkina-faso', label: 'Burkina Faso', phone: '226', code: 'BF', emoji: '🇧🇫' },
  { value: 'burundi', label: 'Burundi', phone: '257', code: 'BI', emoji: '🇧🇮' },
  { value: 'cambodia', label: 'Cambodia', phone: '855', code: 'KH', emoji: '🇰🇭' },
  { value: 'cameroon', label: 'Cameroon', phone: '237', code: 'CM', emoji: '🇨🇲' },
  { value: 'canada', label: 'Canada', phone: '1', code: 'CA', emoji: '🇨🇦' },
  { value: 'cape-verde', label: 'Cape Verde', phone: '238', code: 'CV', emoji: '🇨🇻' },
  { value: 'cayman-islands', label: 'Cayman Islands', phone: '1-345', code: 'KY', emoji: '🇰🇾' },
  { value: 'central-african-republic', label: 'Central African Republic', phone: '236', code: 'CF', emoji: '🇨🇫' },
  { value: 'chad', label: 'Chad', phone: '235', code: 'TD', emoji: '🇹🇩' },
  { value: 'chile', label: 'Chile', phone: '56', code: 'CL', emoji: '🇨🇱' },
  { value: 'china', label: 'China', phone: '86', code: 'CN', emoji: '🇨🇳' },
  { value: 'christmas-island', label: 'Christmas Island', phone: '61', code: 'CX', emoji: '🇨🇽' },
  { value: 'cocos-islands', label: 'Cocos (Keeling) Islands', phone: '61', code: 'CC', emoji: '🇨🇨' },
  { value: 'colombia', label: 'Colombia', phone: '57', code: 'CO', emoji: '🇨🇴' },
  { value: 'comoros', label: 'Comoros', phone: '269', code: 'KM', emoji: '🇰🇲' },
  { value: 'cook-islands', label: 'Cook Islands', phone: '682', code: 'CK', emoji: '🇨🇰' },
  { value: 'costa-rica', label: 'Costa Rica', phone: '506', code: 'CR', emoji: '🇨🇷' },
  { value: 'croatia', label: 'Croatia', phone: '385', code: 'HR', emoji: '🇭🇷' },
  { value: 'cuba', label: 'Cuba', phone: '53', code: 'CU', emoji: '🇨🇺' },
  { value: 'curacao', label: 'Curaçao', phone: '599', code: 'CW', emoji: '🇨🇼' },
  { value: 'cyprus', label: 'Cyprus', phone: '357', code: 'CY', emoji: '🇨🇾' },
  { value: 'czech-republic', label: 'Czech Republic', phone: '420', code: 'CZ', emoji: '🇨🇿' },
  { value: 'democratic-republic-of-congo', label: 'DR Congo', phone: '243', code: 'CD', emoji: '🇨🇩' },
  { value: 'denmark', label: 'Denmark', phone: '45', code: 'DK', emoji: '🇩🇰' },
  { value: 'djibouti', label: 'Djibouti', phone: '253', code: 'DJ', emoji: '🇩🇯' },
  { value: 'dominica', label: 'Dominica', phone: '1-767', code: 'DM', emoji: '🇩🇲' },
  { value: 'dominican-republic', label: 'Dominican Republic', phone: '1-809, 1-829, 1-849', code: 'DO', emoji: '🇩🇴' },
  { value: 'east-timor', label: 'East Timor', phone: '670', code: 'TL', emoji: '🇹🇱' },
  { value: 'ecuador', label: 'Ecuador', phone: '593', code: 'EC', emoji: '🇪🇨' },
  { value: 'egypt', label: 'Egypt', phone: '20', code: 'EG', emoji: '🇪🇬' },
  { value: 'el-salvador', label: 'El Salvador', phone: '503', code: 'SV', emoji: '🇸🇻' },
  { value: 'equatorial-guinea', label: 'Equatorial Guinea', phone: '240', code: 'GQ', emoji: '🇬🇶' },
  { value: 'eritrea', label: 'Eritrea', phone: '291', code: 'ER', emoji: '🇪🇷' },
  { value: 'estonia', label: 'Estonia', phone: '372', code: 'EE', emoji: '🇪🇪' },
  { value: 'ethiopia', label: 'Ethiopia', phone: '251', code: 'ET', emoji: '🇪🇹' },
  { value: 'falkland-islands', label: 'Falkland Islands', phone: '500', code: 'FK', emoji: '🇫🇰' },
  { value: 'faroe-islands', label: 'Faroe Islands', phone: '298', code: 'FO', emoji: '🇫🇴' },
  { value: 'fiji', label: 'Fiji', phone: '679', code: 'FJ', emoji: '🇫🇯' },
  { value: 'finland', label: 'Finland', phone: '358', code: 'FI', emoji: '🇫🇮' },
  { value: 'france', label: 'France', phone: '33', code: 'FR', emoji: '🇫🇷' },
  { value: 'french-polynesia', label: 'French Polynesia', phone: '689', code: 'PF', emoji: '🇵🇫' },
  { value: 'gabon', label: 'Gabon', phone: '241', code: 'GA', emoji: '🇬🇦' },
  { value: 'gambia', label: 'Gambia', phone: '220', code: 'GM', emoji: '🇬🇲' },
  { value: 'georgia', label: 'Georgia', phone: '995', code: 'GE', emoji: '🇬🇪' },
  { value: 'germany', label: 'Germany', phone: '49', code: 'DE', emoji: '🇩🇪' },
  { value: 'ghana', label: 'Ghana', phone: '233', code: 'GH', emoji: '🇬🇭' },
  { value: 'gibraltar', label: 'Gibraltar', phone: '350', code: 'GI', emoji: '🇬🇮' },
  { value: 'greece', label: 'Greece', phone: '30', code: 'GR', emoji: '🇬🇷' },
  { value: 'greenland', label: 'Greenland', phone: '299', code: 'GL', emoji: '🇬🇱' },
  { value: 'grenada', label: 'Grenada', phone: '1-473', code: 'GD', emoji: '🇬🇩' },
  { value: 'guam', label: 'Guam', phone: '1-671', code: 'GU', emoji: '🇬🇺' },
  { value: 'guatemala', label: 'Guatemala', phone: '502', code: 'GT', emoji: '🇬🇹' },
  { value: 'guernsey', label: 'Guernsey', phone: '44-1481', code: 'GG', emoji: '🇬🇬' },
  { value: 'guinea', label: 'Guinea', phone: '224', code: 'GN', emoji: '🇬🇳' },
  { value: 'guinea-bissau', label: 'Guinea-Bissau', phone: '245', code: 'GW', emoji: '🇬🇼' },
  { value: 'guyana', label: 'Guyana', phone: '592', code: 'GY', emoji: '🇬🇾' },
  { value: 'haiti', label: 'Haiti', phone: '509', code: 'HT', emoji: '🇭🇹' },
  { value: 'honduras', label: 'Honduras', phone: '504', code: 'HN', emoji: '🇭🇳' },
  { value: 'hong-kong', label: 'Hong Kong', phone: '852', code: 'HK', emoji: '🇭🇰' },
  { value: 'hungary', label: 'Hungary', phone: '36', code: 'HU', emoji: '🇭🇺' },
  { value: 'iceland', label: 'Iceland', phone: '354', code: 'IS', emoji: '🇮🇸' },
  { value: 'india', label: 'India', phone: '91', code: 'IN', emoji: '🇮🇳' },
  { value: 'indonesia', label: 'Indonesia', phone: '62', code: 'ID', emoji: '🇮🇩' },
  { value: 'iran', label: 'Iran', phone: '98', code: 'IR', emoji: '🇮🇷' },
  { value: 'iraq', label: 'Iraq', phone: '964', code: 'IQ', emoji: '🇮🇶' },
  { value: 'ireland', label: 'Ireland', phone: '353', code: 'IE', emoji: '🇮🇪' },
  { value: 'isle-of-man', label: 'Isle of Man', phone: '44-1624', code: 'IM', emoji: '🇮🇲' },
  { value: 'israel', label: 'Israel', phone: '972', code: 'IL', emoji: '🇮🇱' },
  { value: 'italy', label: 'Italy', phone: '39', code: 'IT', emoji: '🇮🇹' },
  { value: 'ivory-coast', label: 'Ivory Coast', phone: '225', code: 'CI', emoji: '🇨🇮' },
  { value: 'jamaica', label: 'Jamaica', phone: '1-876', code: 'JM', emoji: '🇯🇲' },
  { value: 'japan', label: 'Japan', phone: '81', code: 'JP', emoji: '🇯🇵' },
  { value: 'jersey', label: 'Jersey', phone: '44-1534', code: 'JE', emoji: '🇯🇪' },
  { value: 'jordan', label: 'Jordan', phone: '962', code: 'JO', emoji: '🇯🇴' },
  { value: 'kazakhstan', label: 'Kazakhstan', phone: '7', code: 'KZ', emoji: '🇰🇿' },
  { value: 'kenya', label: 'Kenya', phone: '254', code: 'KE', emoji: '🇰🇪' },
  { value: 'kiribati', label: 'Kiribati', phone: '686', code: 'KI', emoji: '🇰🇮' },
  { value: 'kosovo', label: 'Kosovo', phone: '383', code: 'XK', emoji: '🇽🇰' },
  { value: 'kuwait', label: 'Kuwait', phone: '965', code: 'KW', emoji: '🇰🇼' },
  { value: 'kyrgyzstan', label: 'Kyrgyzstan', phone: '996', code: 'KG', emoji: '🇰🇬' },
  { value: 'laos', label: 'Laos', phone: '856', code: 'LA', emoji: '🇱🇦' },
  { value: 'latvia', label: 'Latvia', phone: '371', code: 'LV', emoji: '🇱🇻' },
  { value: 'lebanon', label: 'Lebanon', phone: '961', code: 'LB', emoji: '🇱🇧' },
  { value: 'lesotho', label: 'Lesotho', phone: '266', code: 'LS', emoji: '🇱🇸' },
  { value: 'liberia', label: 'Liberia', phone: '231', code: 'LR', emoji: '🇱🇷' },
  { value: 'libya', label: 'Libya', phone: '218', code: 'LY', emoji: '🇱🇾' },
  { value: 'liechtenstein', label: 'Liechtenstein', phone: '423', code: 'LI', emoji: '🇱🇮' },
  { value: 'lithuania', label: 'Lithuania', phone: '370', code: 'LT', emoji: '🇱🇹' },
  { value: 'luxembourg', label: 'Luxembourg', phone: '352', code: 'LU', emoji: '🇱🇺' },
  { value: 'macau', label: 'Macau', phone: '853', code: 'MO', emoji: '🇲🇴' },
  { value: 'macedonia', label: 'Macedonia', phone: '389', code: 'MK', emoji: '🇲🇰' },
  { value: 'madagascar', label: 'Madagascar', phone: '261', code: 'MG', emoji: '🇲🇬' },
  { value: 'malawi', label: 'Malawi', phone: '265', code: 'MW', emoji: '🇲🇼' },
  { value: 'malaysia', label: 'Malaysia', phone: '60', code: 'MY', emoji: '🇲🇾' },
  { value: 'maldives', label: 'Maldives', phone: '960', code: 'MV', emoji: '🇲🇻' },
  { value: 'mali', label: 'Mali', phone: '223', code: 'ML', emoji: '🇲🇱' },
  { value: 'malta', label: 'Malta', phone: '356', code: 'MT', emoji: '🇲🇹' },
  { value: 'marshall-islands', label: 'Marshall Islands', phone: '692', code: 'MH', emoji: '🇲🇭' },
  { value: 'mauritania', label: 'Mauritania', phone: '222', code: 'MR', emoji: '🇲🇷' },
  { value: 'mauritius', label: 'Mauritius', phone: '230', code: 'MU', emoji: '🇲🇺' },
  { value: 'mayotte', label: 'Mayotte', phone: '262', code: 'YT', emoji: '🇾🇹' },
  { value: 'mexico', label: 'Mexico', phone: '52', code: 'MX', emoji: '🇲🇽' },
  { value: 'micronesia', label: 'Micronesia', phone: '691', code: 'FM', emoji: '🇫🇲' },
  { value: 'moldova', label: 'Moldova', phone: '373', code: 'MD', emoji: '🇲🇩' },
  { value: 'monaco', label: 'Monaco', phone: '377', code: 'MC', emoji: '🇲🇨' },
  { value: 'mongolia', label: 'Mongolia', phone: '976', code: 'MN', emoji: '🇲🇳' },
  { value: 'montenegro', label: 'Montenegro', phone: '382', code: 'ME', emoji: '🇲🇪' },
  { value: 'montserrat', label: 'Montserrat', phone: '1-664', code: 'MS', emoji: '🇲🇸' },
  { value: 'morocco', label: 'Morocco', phone: '212', code: 'MA', emoji: '🇲🇦' },
  { value: 'mozambique', label: 'Mozambique', phone: '258', code: 'MZ', emoji: '🇲🇿' },
  { value: 'myanmar', label: 'Myanmar', phone: '95', code: 'MM', emoji: '🇲🇲' },
  { value: 'namibia', label: 'Namibia', phone: '264', code: 'NA', emoji: '🇳🇦' },
  { value: 'nauru', label: 'Nauru', phone: '674', code: 'NR', emoji: '🇳🇷' },
  { value: 'nepal', label: 'Nepal', phone: '977', code: 'NP', emoji: '🇳🇵' },
  { value: 'netherlands', label: 'Netherlands', phone: '31', code: 'NL', emoji: '🇳🇱' },
  { value: 'new-caledonia', label: 'New Caledonia', phone: '687', code: 'NC', emoji: '🇳🇨' },
  { value: 'new-zealand', label: 'New Zealand', phone: '64', code: 'NZ', emoji: '🇳🇿' },
  { value: 'nicaragua', label: 'Nicaragua', phone: '505', code: 'NI', emoji: '🇳🇮' },
  { value: 'niger', label: 'Niger', phone: '227', code: 'NE', emoji: '🇳🇪' },
  { value: 'nigeria', label: 'Nigeria', phone: '234', code: 'NG', emoji: '🇳🇬' },
  { value: 'niue', label: 'Niue', phone: '683', code: 'NU', emoji: '🇳🇺' },
  { value: 'north-korea', label: 'North Korea', phone: '850', code: 'KP', emoji: '🇰🇵' },
  { value: 'northern-mariana-islands', label: 'Northern Mariana Islands', phone: '1-670', code: 'MP', emoji: '🇲🇵' },
  { value: 'norway', label: 'Norway', phone: '47', code: 'NO', emoji: '🇳🇴' },
  { value: 'oman', label: 'Oman', phone: '968', code: 'OM', emoji: '🇴🇲' },
  { value: 'pakistan', label: 'Pakistan', phone: '92', code: 'PK', emoji: '🇵🇰' },
  { value: 'palau', label: 'Palau', phone: '680', code: 'PW', emoji: '🇵🇼' },
  { value: 'palestine', label: 'Palestine', phone: '970', code: 'PS', emoji: '🇵🇸' },
  { value: 'panama', label: 'Panama', phone: '507', code: 'PA', emoji: '🇵🇦' },
  { value: 'papua-new-guinea', label: 'Papua New Guinea', phone: '675', code: 'PG', emoji: '🇵🇬' },
  { value: 'paraguay', label: 'Paraguay', phone: '595', code: 'PY', emoji: '🇵🇾' },
  { value: 'peru', label: 'Peru', phone: '51', code: 'PE', emoji: '🇵🇪' },
  { value: 'philippines', label: 'Philippines', phone: '63', code: 'PH', emoji: '🇵🇭' },
  { value: 'pitcairn-islands', label: 'Pitcairn Islands', phone: '64', code: 'PN', emoji: '🇵🇳' },
  { value: 'poland', label: 'Poland', phone: '48', code: 'PL', emoji: '🇵🇱' },
  { value: 'portugal', label: 'Portugal', phone: '351', code: 'PT', emoji: '🇵🇹' },
  { value: 'puerto-rico', label: 'Puerto Rico', phone: '1-787, 1-939', code: 'PR', emoji: '🇵🇷' },
  { value: 'qatar', label: 'Qatar', phone: '974', code: 'QA', emoji: '🇶🇦' },
  { value: 'republic-of-congo', label: 'Republic of the Congo', phone: '242', code: 'CG', emoji: '🇨🇬' },
  { value: 'reunion', label: 'Réunion', phone: '262', code: 'RE', emoji: '🇷🇪' },
  { value: 'romania', label: 'Romania', phone: '40', code: 'RO', emoji: '🇷🇴' },
  { value: 'russia', label: 'Russia', phone: '7', code: 'RU', emoji: '🇷🇺' },
  { value: 'rwanda', label: 'Rwanda', phone: '250', code: 'RW', emoji: '🇷🇼' },
  { value: 'saint-barthelemy', label: 'Saint Barthélemy', phone: '590', code: 'BL', emoji: '🇧🇱' },
  { value: 'saint-helena', label: 'Saint Helena', phone: '290', code: 'SH', emoji: '🇸🇭' },
  { value: 'saint-kitts-and-nevis', label: 'Saint Kitts and Nevis', phone: '1-869', code: 'KN', emoji: '🇰🇳' },
  { value: 'saint-lucia', label: 'Saint Lucia', phone: '1-758', code: 'LC', emoji: '🇱🇨' },
  { value: 'saint-martin', label: 'Saint Martin', phone: '590', code: 'MF', emoji: '🇲🇫' },
  { value: 'saint-pierre-and-miquelon', label: 'Saint Pierre and Miquelon', phone: '508', code: 'PM', emoji: '🇵🇲' },
  { value: 'saint-vincent-and-the-grenadines', label: 'St. Vincent & Grenadines', phone: '1-784', code: 'VC', emoji: '🇻🇨' },
  { value: 'samoa', label: 'Samoa', phone: '685', code: 'WS', emoji: '🇼🇸' },
  { value: 'san-marino', label: 'San Marino', phone: '378', code: 'SM', emoji: '🇸🇲' },
  { value: 'sao-tome-and-principe', label: 'São Tomé and Príncipe', phone: '239', code: 'ST', emoji: '🇸🇹' },
  { value: 'saudi-arabia', label: 'Saudi Arabia', phone: '966', code: 'SA', emoji: '🇸🇦' },
  { value: 'senegal', label: 'Senegal', phone: '221', code: 'SN', emoji: '🇸🇳' },
  { value: 'serbia', label: 'Serbia', phone: '381', code: 'RS', emoji: '🇷🇸' },
  { value: 'seychelles', label: 'Seychelles', phone: '248', code: 'SC', emoji: '🇸🇨' },
  { value: 'sierra-leone', label: 'Sierra Leone', phone: '232', code: 'SL', emoji: '🇸🇱' },
  { value: 'singapore', label: 'Singapore', phone: '65', code: 'SG', emoji: '🇸🇬' },
  { value: 'sint-maarten', label: 'Sint Maarten', phone: '1-721', code: 'SX', emoji: '🇸🇽' },
  { value: 'slovakia', label: 'Slovakia', phone: '421', code: 'SK', emoji: '🇸🇰' },
  { value: 'slovenia', label: 'Slovenia', phone: '386', code: 'SI', emoji: '🇸🇮' },
  { value: 'solomon-islands', label: 'Solomon Islands', phone: '677', code: 'SB', emoji: '🇸🇧' },
  { value: 'somalia', label: 'Somalia', phone: '252', code: 'SO', emoji: '🇸🇴' },
  { value: 'south-africa', label: 'South Africa', phone: '27', code: 'ZA', emoji: '🇿🇦' },
  { value: 'south-korea', label: 'South Korea', phone: '82', code: 'KR', emoji: '🇰🇷' },
  { value: 'south-sudan', label: 'South Sudan', phone: '211', code: 'SS', emoji: '🇸🇸' },
  { value: 'spain', label: 'Spain', phone: '34', code: 'ES', emoji: '🇪🇸' },
  { value: 'sri-lanka', label: 'Sri Lanka', phone: '94', code: 'LK', emoji: '🇱🇰' },
  { value: 'sudan', label: 'Sudan', phone: '249', code: 'SD', emoji: '🇸🇩' },
  { value: 'suriname', label: 'Suriname', phone: '597', code: 'SR', emoji: '🇸🇷' },
  { value: 'svalbard-and-jan-mayen', label: 'Svalbard and Jan Mayen', phone: '47', code: 'SJ', emoji: '🇸🇯' },
  { value: 'swaziland', label: 'Swaziland', phone: '268', code: 'SZ', emoji: '🇸🇿' },
  { value: 'sweden', label: 'Sweden', phone: '46', code: 'SE', emoji: '🇸🇪' },
  { value: 'switzerland', label: 'Switzerland', phone: '41', code: 'CH', emoji: '🇨🇭' },
  { value: 'syria', label: 'Syria', phone: '963', code: 'SY', emoji: '🇸🇾' },
  { value: 'taiwan', label: 'Taiwan', phone: '886', code: 'TW', emoji: '🇹🇼' },
  { value: 'tajikistan', label: 'Tajikistan', phone: '992', code: 'TJ', emoji: '🇹🇯' },
  { value: 'tanzania', label: 'Tanzania', phone: '255', code: 'TZ', emoji: '🇹🇿' },
  { value: 'thailand', label: 'Thailand', phone: '66', code: 'TH', emoji: '🇹🇭' },
  { value: 'togo', label: 'Togo', phone: '228', code: 'TG', emoji: '🇹🇬' },
  { value: 'tokelau', label: 'Tokelau', phone: '690', code: 'TK', emoji: '🇹🇰' },
  { value: 'tonga', label: 'Tonga', phone: '676', code: 'TO', emoji: '🇹🇴' },
  { value: 'trinidad-and-tobago', label: 'Trinidad and Tobago', phone: '1-868', code: 'TT', emoji: '🇹🇹' },
  { value: 'tunisia', label: 'Tunisia', phone: '216', code: 'TN', emoji: '🇹🇳' },
  { value: 'turkey', label: 'Turkey', phone: '90', code: 'TR', emoji: '🇹🇷' },
  { value: 'turkmenistan', label: 'Turkmenistan', phone: '993', code: 'TM', emoji: '🇹🇲' },
  { value: 'turks-and-caicos-islands', label: 'Turks and Caicos Islands', phone: '1-649', code: 'TC', emoji: '🇹🇨' },
  { value: 'tuvalu', label: 'Tuvalu', phone: '688', code: 'TV', emoji: '🇹🇻' },
  { value: 'uganda', label: 'Uganda', phone: '256', code: 'UG', emoji: '🇺🇬' },
  { value: 'ukraine', label: 'Ukraine', phone: '380', code: 'UA', emoji: '🇺🇦' },
  { value: 'united-arab-emirates', label: 'United Arab Emirates', phone: '971', code: 'AE', emoji: '🇦🇪' },
  { value: 'united-kingdom', label: 'United Kingdom', phone: '44', code: 'GB', emoji: '🇬🇧' },
  { value: 'united-states', label: 'United States', phone: '1', code: 'US', emoji: '🇺🇸' },
  { value: 'us-virgin-islands', label: 'U.S. Virgin Islands', phone: '1-340', code: 'VI', emoji: '🇻🇮' },
  { value: 'uruguay', label: 'Uruguay', phone: '598', code: 'UY', emoji: '🇺🇾' },
  { value: 'uzbekistan', label: 'Uzbekistan', phone: '998', code: 'UZ', emoji: '🇺🇿' },
  { value: 'vanuatu', label: 'Vanuatu', phone: '678', code: 'VU', emoji: '🇻🇺' },
  { value: 'vatican-city', label: 'Vatican City', phone: '379', code: 'VA', emoji: '🇻🇦' },
  { value: 'venezuela', label: 'Venezuela', phone: '58', code: 'VE', emoji: '🇻🇪' },
  { value: 'vietnam', label: 'Vietnam', phone: '84', code: 'VN', emoji: '🇻🇳' },
  { value: 'wallis-and-futuna', label: 'Wallis and Futuna', phone: '681', code: 'WF', emoji: '🇼🇫' },
  { value: 'western-sahara', label: 'Western Sahara', phone: '212', code: 'EH', emoji: '🇪🇭' },
  { value: 'yemen', label: 'Yemen', phone: '967', code: 'YE', emoji: '🇾🇪' },
  { value: 'zambia', label: 'Zambia', phone: '260', code: 'ZM', emoji: '🇿🇲' },
  { value: 'zimbabwe', label: 'Zimbabwe', phone: '263', code: 'ZW', emoji: '🇿🇼' },
];
